name: Run Tests and Coverage

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    name: Flake8 Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 (without complexity check failing CI)
        run: flake8 --ignore=C901

        # Temporary until the Complexity are solved
      - name: Run Complexity Check (Warnings Only)
        id: complexity_check
        run: |
          WARNINGS=$(flake8 --select=C901 | tee complexity_warnings.log | wc -l)
          echo "Number of complexity warnings: $WARNINGS"
          
          if [ "$WARNINGS" -gt 0 ]; then
            echo "Complexity warnings detected but not failing build."
            
            # Add a warning message to GitHub Actions summary
            echo "### ⚠️ Complexity Warnings Detected" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Flake8 found **$WARNINGS** complexity warnings. Please refactor the affected functions!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### Affected Files:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat complexity_warnings.log >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Change this if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run Tests and Measure Coverage
        run: pytest

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}  # Set this in your repository secrets
