[[pages]]
path = 'src/pages/main_page.py'
name = 'Bee Balanced'
icon = ':bar_chart:'

[[pages]]
path = 'src/pages/comments_list_page.py'
name = 'Comments List'
icon = ':notebook:'

[[pages]]
path = 'src/pages/top_holders_page.py'
name = 'Top Holders'
icon = ':technologist:'

[[pages]]
path = 'src/pages/custom_queries_page.py'
name = 'Custom Queries'
icon = ':technologist:'
